### ISSUE TITLE
SimpleMDE wont save

### ISSUE THREAD

**Issue by YTW** [bleutzinn/grav-plugin-editable#7]
I'm having an issue with SimpleMDE editable plugin. It won't save when i click the tick button it just displays an X. I have created a modular page as seen in the screenshot below. Any idea what the issue is?

![-getgrav-fb1o-2017051716 00 59capture png](https://cloud.githubusercontent.com/assets/8450674/26169773/c3d8bb48-3b36-11e7-892b-764ffc9cea64.jpg)

Live Example: http://recordit.co/FE7datDeJi

**Comment by bleutzinn** [comment]
Please check that the page content is HTML. If it is not, ContentTools is not able to save.

**Comment by YTW** [comment]
This is the current settings under the 'content' page. How do i make sure it is HTML?

```
title: content
process:
    markdown: true
    twig: true
content:
    items: '@self.modular'
    order:
        by: date
        dir: desc
```

**Comment by bleutzinn** [comment]
I reopened this issue because on May 29th, 2017 I received a message from YTW via email from GitHub. But for some reason that message is not viewable in this GitHub page. Therefor I pasted it below:

YTW wrote:
"This is the current settings under the 'content' page. How do i make sure it is HTML?
```
title: content
process:
    markdown: true
    twig: true
content:
    items: '@self.modular'
    order:
        by: date
        dir: desc
```
"

Editable content must be stored in the `default.md` file of a normal Grav page. The frontmatter you sent indicates that the page is a modular page where the content is dynamically assembled from the content of each modular child page. So Editable with either SimpleMDE or ContentTools (in this case it doesn't matter which) can't edit the content directly so it won't work with your setup.

Depending on the need and why the child pages are modular pages, one option is to change these child pages from modular pages to normal pages. The modular parent page will still be able to assemble it's content from the child pages. That parent page will still not be editable but each child page could be.

To prevent unwanted edits on modular pages you can best set `editable_self: false` for the complete website in the file `user/config/plugins/editable.yaml` and enable the Editable Self mode on each normal page that you want to make editable.

You can enter HTML in the content just like you enter markdown. For example, this is a valid normal Grav page which uses HTML and can be edited in the front-end with the ContentTools editor:
```
---
title: My page
editable:
    editable_self: true
---
<h2>Hello World</h2>
```
